//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Билет
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Билет()
        {
            this.Пассажировместимость = new HashSet<Пассажировместимость>();
        }
    
        public int ID_билета { get; set; }
        public Nullable<int> ID_пассажира { get; set; }
        public Nullable<int> ID_рейса { get; set; }
    
        public virtual Пассажир Пассажир { get; set; }
        public virtual Расписание_рейсов Расписание_рейсов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пассажировместимость> Пассажировместимость { get; set; }
    }
}
