//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Маршрут
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Маршрут()
        {
            this.Расписание_рейсов = new HashSet<Расписание_рейсов>();
        }
    
        public int ID_маршрута { get; set; }
        public string Название_маршрута { get; set; }
        public Nullable<int> ID_рейса { get; set; }
        public Nullable<int> ID_автобуса { get; set; }
        public Nullable<int> ID_деспетчера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание_рейсов> Расписание_рейсов { get; set; }
    }
}
