//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание_рейсов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Расписание_рейсов()
        {
            this.Билет = new HashSet<Билет>();
        }
    
        public int ID_рейса { get; set; }
        public Nullable<System.TimeSpan> Время_отправки { get; set; }
        public Nullable<System.TimeSpan> Время_прибытия { get; set; }
        public string Статус_рейса { get; set; }
        public Nullable<int> ID_водителя { get; set; }
        public Nullable<int> ID_маршрута { get; set; }
        public string Название_рейса { get; set; }
        public int ID_диспетчера { get; set; }
        public Nullable<int> ID_автобуса { get; set; }
        public Nullable<int> ID_билета { get; set; }
    
        public virtual Автобус Автобус { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Билет> Билет { get; set; }
        public virtual Водители Водители { get; set; }
        public virtual Диспетчер Диспетчер { get; set; }
        public virtual Маршрут Маршрут { get; set; }
    }
}
